sudo: required

language: go
go:
  - "1.10"

services:
  - docker

env: 
  - IMAGE=julglotain/go-middleware-ctx-example:1.0

before_script:
  - docker build -t ${IMAGE} .
  - docker run -d -p 127.0.0.1:8085:8085 ${IMAGE}
  - docker ps -a

script: 
  - curl 127.0.0.1:8085/status

deploy: 
  provider: script
  script: bash docker_push.sh
  on:  
    branch: master