sudo: required

services:
  - docker

env: 
  - IMAGE_NAME="julglotain/go-middleware-ctx-example" IMAGE_VERSION="1.0"

before_script:
  - docker build -t ${IMAGE_NAME}:${IMAGE_VERSION} .
  - docker run -d -p 127.0.0.1:8085:8085 ${IMAGE_NAME}:${IMAGE_VERSION}
  - docker ps -a

script: 
  - curl 127.0.0.1:8085/status

deploy: 
  provider: script
  script: bash docker_push.sh
  on:  
    branch: master